// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGggvtz-HQjBvU--uaWp_nddZWfJHtac4',
    appId: '1:911135110285:web:c12cf13a68912bfdb99ec4',
    messagingSenderId: '911135110285',
    projectId: 'portfolio-4b69b',
    authDomain: 'portfolio-4b69b.firebaseapp.com',
    storageBucket: 'portfolio-4b69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1bsS7tP1DRQKWOKQAK85Nv-HKlj8K4U',
    appId: '1:911135110285:android:fa7da0aee06a1693b99ec4',
    messagingSenderId: '911135110285',
    projectId: 'portfolio-4b69b',
    storageBucket: 'portfolio-4b69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5otoqYCT7EGhB94lEpyude9gxay-KenE',
    appId: '1:911135110285:ios:47b98d7f55f003a7b99ec4',
    messagingSenderId: '911135110285',
    projectId: 'portfolio-4b69b',
    storageBucket: 'portfolio-4b69b.appspot.com',
    iosClientId: '911135110285-jnvio37gk1vl17hnit40j0sr4ghm2vei.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5otoqYCT7EGhB94lEpyude9gxay-KenE',
    appId: '1:911135110285:ios:47b98d7f55f003a7b99ec4',
    messagingSenderId: '911135110285',
    projectId: 'portfolio-4b69b',
    storageBucket: 'portfolio-4b69b.appspot.com',
    iosClientId: '911135110285-jnvio37gk1vl17hnit40j0sr4ghm2vei.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolioDev',
  );
}
